### PR TITLE
adding useFFI cabal flag

### PR DESCRIPTION
**Pull request by Keyholder**
windows users need this because of https://ghc.haskell.org/trac/ghc/ticket/3242

### CODE REVIEW

**Comment by ekmett** [comment]
Alternately we could just detect os(windows) and apply the same logic.

This gets a bit more complicated though, ghc 7.10 adds the log1p, expm1, etc. combinators as primitives.

**Comment by Keyholder** [comment]
If so, we need three-way detection. One path for ghc above 7.10, another for windows, and third for everything else. Though, I'm not very familiar with your coding style, so patch of this complexity may be above my competency in this case.

**Comment by cmears** [comment]
It would be great to have this change merged -- I can't get log-domain to work on Windows without it. Is there any testing I can do to help? (I have convenient access to Windows and Mac and Linux systems to test on.)

**Comment by Keyholder** [comment]
As you can see above, ekmett suggested that patch with autodetection instead of cabal flag would be more suitable for master branch merging. I fully agree with this, but unfortunately I'm too distracted this days to rewrite patch myself. So, I suppose it's more about coding then testing right now.

**Comment by cmears** [comment]
Is the change then just a matter of removing the useFFI flag and saying "if os(windows)"? See my potential patch: cmears@6be1cfc . It does seem to work on Windows. I first tried to handle GHC 7.10 as well, but couldn't get log-domain's dependencies to build.

**Comment by Keyholder** [comment]
Lol. I didn't knew that "os(windows)" is actually legal cabal expression.
Before I have seen some old code where people were querying environment in
more complex ways and naturally thought that it's a bit harder to do. Nice!
15 Мар 2015 г. 14:51 пользователь "Edward Kmett" <notifications@github.com>
написал:

**Pull request merged**
