### PR TITLE
vector-0.11 is out

### PR DESCRIPTION
**Pull request by Keyholder**
Compiling with new version seems fine for me.

### CODE REVIEW

**Comment by glguy** [comment]
src/Numeric/Log.hs:359:10: Warning:
        No explicit method or default declaration for `basicInitialize'
        In the instance declaration for `M.MVector U.MVector (Log a)'

The class for a new method in 0.11

**Comment by Keyholder** [comment]
Ok, that's embarrassing - I somehow managed to miss this warning. Looks like basicInitialize is in new minimal complete definition for M.MVector while being absent from previous versions at all. That's sad because it means that same code can't be compiled against 0.11 and previous versions simultaneously. Either dropping support for < 0.11 or surrounding basicInitialize implementation with preprocessor version checking is in order. What would maintainers prefer?

**Comment by cartazio** [comment]
Cpp it!

**Comment by Keyholder** [comment]
Done!

**Pull request merged**
